Project #4 of HTML-CSS Course
KennyUTN/Apple-ClonePage-Kenny pull request #2
Opened 2020-05-07 15:59 UTC by KennyUTN

Worked alone with permission from the student success team.

2020-05-08 12:08 UTC, trekab requested changes
# Changes required:
Well done @KennyUTN. :clap: You have done an impressive job on this project. I have noticed a heavy use of `<div>` tags in your HTML. This directs me to the required changes you need to make in your project. 
- [ ] Make use of [semantic HTML](https://www.w3schools.com/html/html5_semantic_elements.asp) elements whenever possible. Please refine your HTML to rely more on semantic tags.
- [ ] The four bottom elements with more images, should be links.

## Optional:
- Position the search icon inside the search input to make it look more like the original site.
- Check out [Why use semantic tags](https://hackernoon.com/why-you-should-add-html5-markup-even-if-there-is-no-visual-effect-on-the-page-f49u32ca) article about the importance of semantic HTML.

__Kindly work on the required changes and submit another code review request__
_Feel free to contact me on slack for any inquiries about this review_ :wink: 
__Treasure Kabareebe__

2020-05-09 15:06 UTC, rammazzoti2000 requested changes
### Hello @KennyUTN :raised_hands: you did great on the project.
Great job on implementing the changes required by the previous TSE :clap: 

- I see you made use of CSS background property for your main image content
- Also you used CSS background gradient property on your navigation :muscle: 
But there are still some issues we need to fix before approving this project.
### :stop_sign: Required Changes :construction: :construction_worker: 
- [ ] The Pull Request must have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] The preview screenshot in the readme is quite long, the upper part shows the website and the bottom part is just white blank, please use a better screenshot, is taking critical space on your readme for no reason 
- [ ] In navbar, the logo and the search input are a bit misaligned
#### Original:
![image](https://user-images.githubusercontent.com/3244654/81476695-8d3f6f00-9213-11ea-97c5-5e9c4e7430de.png)
#### Clone:
![image](https://user-images.githubusercontent.com/3244654/81476720-ad6f2e00-9213-11ea-9ff5-e0ce1c1fe8bf.png)
- [ ] Your website should stretch on the entire width of the page, yours is not this is beacause of the added margin in the body 
- [ ] Try to improve the typography on your page, it should match as much as possible the one used in the original, apply this font to html element to use it globally:  `font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;`
- [ ] The navbar should be a `nav` element, let's use HTML semantic, please.
- [ ] The page has a heavy horizontal overflow caused by `phonesContainer`, mainly beacause is inside the wrong container, also because of the added margins in the `body`, move it outside the header to stop the overflow.
- [ ] The footer should be like on the original website
#### Clone:
![image](https://user-images.githubusercontent.com/3244654/81476896-c62c1380-9214-11ea-91dd-eb2636a70131.png)
#### Original: 
![image](https://user-images.githubusercontent.com/3244654/81476915-ed82e080-9214-11ea-994e-badbc5162a24.png)
#
### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

##### Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of alexandru if you have any additional question)</em>

### :stop_sign:  Status: Changes required.

2020-05-09 15:06 UTC, rammazzoti2000 commented on README.md
> +![](img/preview1.png)
The preview screenshot in the readme is quite long, the upper part shows the website and the bottom part is just white blank, please use a better screenshot, is taking critical space on your readme for no reason

2020-05-09 15:06 UTC, rammazzoti2000 commented on index.html
> +      <div class="navBar">
You used header element but you didn't use nav element. Please make this div container a nav element

2020-05-09 15:06 UTC, rammazzoti2000 commented on index.html
> +    <div class="phonesContainer">
This is overflowing outside your header container creating bad alignment. I think it could be moved outside the header. Also is causing heavy horizontal overflow on the page.

2020-05-09 15:06 UTC, rammazzoti2000 commented on style.css
> +body {
Remove the margin property to allow the website to display on the entire width of the page

2020-05-09 15:06 UTC, rammazzoti2000 requested changes
### :stop_sign: Status: Required Changes

2020-05-11 18:14 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-11 18:23 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi **TEAM**, you did a great job with this project :smile: Congratulations for the hard work :+1: 
However, we need to apply the DRY rule to our CSS file. Kindly check the comment below:
```
.phone1, phone2, phone3, phone4 {
       border: 3px solid white;
       width: 360px;
       height: 200px;
}
```
And apply their respective background-images to them

KIndly make these change and submit another code review :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

2020-05-11 22:29 UTC, addod19 approved these changes
## Status: Approved :trophy: :airplane: 

Hi @KennyUTN, congratulations on this project :+1: You did the refactor nicely but there appears another problem, which is the horizontal scroll. It is easily fixable by adding a ```width:100% to the .phonesContainer``` **line 89**
Kindly address this issue before you merge. It is very important, otherwise, I would have asked you to submit another code review for that :+1: 

Do not forget to make the change and merge to master :smile: 
Good luck with your next projects
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-12 20:45 UTC, merged